### ISSUE TITLE
No recent changes

### ISSUE THREAD

**Issue by tidymonkey81** [Ahmad-A0/Edulink-API#10]
I'd like to go down this route and explore, but does anyone know if these calls still work? thanks.

**Comment by Ahmad-A0** [comment]
AFAIK everything still works, I was using it to poll my homeworks on the daily until a couple of weeks ago. The documentation is still lacking but if you have any questions let me know. @tidymonkey81

**Comment by tidymonkey81** [comment]
Amazing, I'll have a look.
